/* ============================================
   JAMCY Radar — game-data.js
   Copyright (C) 2026 JAMCY (jamcymeme)
   Licensed under AGPL-3.0 — see LICENSE
   ============================================ */

'use strict';

// outcome: "rug" | "moon"
// difficulty: "easy" | "medium" | "hard"
const GAME_TOKENS = [

  // ── EASY RUGS ───────────────────────────────────────────────
  {
    name: 'SafeAIElon',
    symbol: 'SAIE',
    difficulty: 'easy',
    outcome: 'rug',
    emoji: '🍯',
    stats: {
      holders: 1,
      buyTax: '0%',
      sellTax: '99%',
      liquidity: '$0',
      topHolder: '99%',
      openSource: false,
      deployer: 'Fresh wallet · 0 prior launches',
      raised: '$3',
    },
    reveal: '99% sell tax — textbook honeypot. You could buy but never sell.',
  },
  {
    name: 'DogeGPT',
    symbol: 'DGPT',
    difficulty: 'easy',
    outcome: 'rug',
    emoji: '👻',
    stats: {
      holders: 3,
      buyTax: '5%',
      sellTax: '5%',
      liquidity: '$0',
      topHolder: '92%',
      openSource: false,
      deployer: 'Fresh wallet · 0 prior launches',
      raised: '$0',
    },
    reveal: '$0 raised, 3 holders, 92% in one wallet — ghost launch. Never had real buyers.',
  },
  {
    name: 'ZeroTaxTrap',
    symbol: 'ZTT',
    difficulty: 'easy',
    outcome: 'rug',
    emoji: '🪤',
    stats: {
      holders: 8,
      buyTax: '0%',
      sellTax: '0%',
      liquidity: '$0',
      topHolder: '88%',
      openSource: false,
      deployer: 'Fresh wallet · 0 prior launches',
      raised: '$44',
    },
    reveal: '0/0 tax is bait. 8 holders, $44 raised, 88% in one wallet — a pre-rug setup.',
  },
  {
    name: 'PepeWorldOrder',
    symbol: 'PWO',
    difficulty: 'easy',
    outcome: 'rug',
    emoji: '🚩',
    stats: {
      holders: 2,
      buyTax: '0%',
      sellTax: '0%',
      liquidity: '$0',
      topHolder: '98%',
      openSource: false,
      deployer: 'Serial rugger · 8 prior rugs',
      raised: '$15',
    },
    reveal: '0/0 tax looks great — but the deployer has 8 confirmed rugs. Always check deployer history.',
  },

  // ── EASY MOONS ──────────────────────────────────────────────
  {
    name: 'GreenPepe',
    symbol: 'GPEPE',
    difficulty: 'easy',
    outcome: 'moon',
    emoji: '✅',
    stats: {
      holders: 1842,
      buyTax: '0%',
      sellTax: '0%',
      liquidity: '$94,000 (locked 1 year)',
      topHolder: '4%',
      openSource: true,
      deployer: 'Clean · 2 successful launches',
      raised: '$94,000',
    },
    reveal: 'Clean across the board — locked LP, 1800+ holders, 0/0 tax, open source, experienced deployer.',
  },
  {
    name: 'ApeStronger',
    symbol: 'APES',
    difficulty: 'easy',
    outcome: 'moon',
    emoji: '🦍',
    stats: {
      holders: 623,
      buyTax: '1%',
      sellTax: '1%',
      liquidity: '$31,000 (locked 6 months)',
      topHolder: '6%',
      openSource: true,
      deployer: 'Clean · 1 graduated launch',
      raised: '$31,000',
    },
    reveal: 'Locked liquidity, open source, deployer with a graduation on record. Solid fundamentals.',
  },
  {
    name: 'BasedFrog',
    symbol: 'BFROG',
    difficulty: 'easy',
    outcome: 'moon',
    emoji: '🐸',
    stats: {
      holders: 4210,
      buyTax: '0%',
      sellTax: '0%',
      liquidity: '$180,000 (locked 2 years)',
      topHolder: '2%',
      openSource: true,
      deployer: 'Clean · 4 successful launches',
      raised: '$180,000',
    },
    reveal: '4200+ holders, 2-year LP lock, 0/0 tax, experienced deployer. As clean as it gets.',
  },

  // ── MEDIUM RUGS ─────────────────────────────────────────────
  {
    name: 'TrumpMint2026',
    symbol: 'MINT26',
    difficulty: 'medium',
    outcome: 'rug',
    emoji: '💧',
    stats: {
      holders: 47,
      buyTax: '2%',
      sellTax: '2%',
      liquidity: '$1,240 (unlocked)',
      topHolder: '24%',
      openSource: true,
      deployer: 'Clean · 2 prior launches',
      raised: '$1,240',
    },
    reveal: 'Looks decent — but liquidity was unlocked. Devs drained it the moment it pumped.',
  },
  {
    name: 'AIChainX',
    symbol: 'AICX',
    difficulty: 'medium',
    outcome: 'rug',
    emoji: '🔓',
    stats: {
      holders: 112,
      buyTax: '5%',
      sellTax: '5%',
      liquidity: '$8,400 (unlocked)',
      topHolder: '18%',
      openSource: false,
      deployer: 'Risky · 1 prior rug',
      raised: '$8,400',
    },
    reveal: 'Decent numbers but unlocked liquidity + closed source + risky deployer. Pulled after 6 hours.',
  },
  {
    name: 'ShibaBlackHole',
    symbol: 'SHIBH',
    difficulty: 'medium',
    outcome: 'rug',
    emoji: '🕳️',
    stats: {
      holders: 28,
      buyTax: '3%',
      sellTax: '3%',
      liquidity: '$0',
      topHolder: '55%',
      openSource: true,
      deployer: 'Fresh wallet · 0 prior launches',
      raised: '$280',
    },
    reveal: 'Open source is a green flag, but 55% in one wallet + fresh deployer + no liquidity = exit.',
  },

  // ── MEDIUM MOONS ────────────────────────────────────────────
  {
    name: 'ChadToken',
    symbol: 'CHAD',
    difficulty: 'medium',
    outcome: 'moon',
    emoji: '💪',
    stats: {
      holders: 287,
      buyTax: '3%',
      sellTax: '5%',
      liquidity: '$14,500 (locked 1 year)',
      topHolder: '9%',
      openSource: true,
      deployer: 'Clean · 0 prior launches',
      raised: '$14,500',
    },
    reveal: "First launch for this deployer but solid structure — locked LP, open source, healthy distribution.",
  },
  {
    name: 'BabyWifHat',
    symbol: 'BWIF',
    difficulty: 'medium',
    outcome: 'moon',
    emoji: '🌱',
    stats: {
      holders: 38,
      buyTax: '0%',
      sellTax: '0%',
      liquidity: '$2,100 (locked 1 year)',
      topHolder: '14%',
      openSource: true,
      deployer: 'Clean · 0 prior launches',
      raised: '$2,100',
    },
    reveal: 'Low holder count = early stage, not a red flag. LP locked a year, open source. Early gem.',
  },
  {
    name: 'CryptoKittenX',
    symbol: 'CKX',
    difficulty: 'medium',
    outcome: 'moon',
    emoji: '🐱',
    stats: {
      holders: 156,
      buyTax: '5%',
      sellTax: '5%',
      liquidity: '$7,800 (locked 1 year)',
      topHolder: '10%',
      openSource: true,
      deployer: 'Clean · 2 graduated launches',
      raised: '$7,800',
    },
    reveal: 'Moderate taxes but deployer has 2 graduations. Locked LP and open source confirm legitimacy.',
  },

  // ── HARD RUGS (counter-intuitive) ───────────────────────────
  {
    name: 'HoneyBadgerInu',
    symbol: 'HBINU',
    difficulty: 'hard',
    outcome: 'rug',
    emoji: '⏳',
    stats: {
      holders: 340,
      buyTax: '0%',
      sellTax: '0%',
      liquidity: '$22,000 (locked 30 days)',
      topHolder: '12%',
      openSource: true,
      deployer: 'Clean · 3 prior launches',
      raised: '$22,000',
    },
    reveal: 'Locked only 30 days — devs waited, then drained on day 31. Always check the lock duration.',
  },
  {
    name: 'NakamotoRevival',
    symbol: 'NKMT',
    difficulty: 'hard',
    outcome: 'rug',
    emoji: '🎭',
    stats: {
      holders: 201,
      buyTax: '0%',
      sellTax: '0%',
      liquidity: '$11,000 (locked 1 year)',
      topHolder: '8%',
      openSource: false,
      deployer: 'Risky · 2 prior rugs',
      raised: '$11,000',
    },
    reveal: '0/0 tax + locked LP looked great. Closed source hid a backdoor. Deployer had 2 prior rugs.',
  },
  {
    name: 'PolitiFi2026',
    symbol: 'POLI',
    difficulty: 'hard',
    outcome: 'rug',
    emoji: '🖨️',
    stats: {
      holders: 520,
      buyTax: '2%',
      sellTax: '2%',
      liquidity: '$28,000 (locked 3 months)',
      topHolder: '7%',
      openSource: true,
      deployer: 'Clean · 1 prior launch',
      raised: '$28,000',
    },
    reveal: 'Everything looked fine — but a hidden mint function let devs print tokens and dump on holders.',
  },

  // ── HARD MOONS (counter-intuitive) ──────────────────────────
  {
    name: 'MegaDoge3000',
    symbol: 'MD3K',
    difficulty: 'hard',
    outcome: 'moon',
    emoji: '💸',
    stats: {
      holders: 92,
      buyTax: '10%',
      sellTax: '10%',
      liquidity: '$5,200 (locked 6 months)',
      topHolder: '11%',
      openSource: true,
      deployer: 'Clean · 1 prior launch',
      raised: '$5,200',
    },
    reveal: 'High taxes look scary but fund marketing. Locked LP + open source = legitimate. Tax ≠ rug.',
  },
  {
    name: 'AnonDevCoin',
    symbol: 'ANON',
    difficulty: 'hard',
    outcome: 'moon',
    emoji: '🤐',
    stats: {
      holders: 44,
      buyTax: '0%',
      sellTax: '0%',
      liquidity: '$3,600 (locked 1 year)',
      topHolder: '16%',
      openSource: false,
      deployer: 'Clean · 0 prior launches',
      raised: '$3,600',
    },
    reveal: 'Closed source is a yellow flag but everything else checks out. Low holder count = early stage.',
  },
  {
    name: 'SolanaRocket',
    symbol: 'SLRKT',
    difficulty: 'hard',
    outcome: 'moon',
    emoji: '🚀',
    stats: {
      holders: 890,
      buyTax: '0%',
      sellTax: '0%',
      liquidity: '$67,000 (locked 2 years)',
      topHolder: '5%',
      openSource: true,
      deployer: 'Clean · 3 successful launches',
      raised: '$67,000',
    },
    reveal: 'Nearly 900 holders, 2-year LP lock, experienced deployer with 3 wins. Strong community signal.',
  },

  // ── REAL-WORLD CASES ────────────────────────────────────────

  // RUGS
  {
    name: 'Squid Game Token',
    symbol: 'SQUID',
    difficulty: 'hard',
    outcome: 'rug',
    emoji: '🦑',
    real: true,
    stats: {
      holders: 40000,
      buyTax: '0%',
      sellTax: '100% (hidden)',
      liquidity: '$3,380,000 (unlocked)',
      topHolder: 'Unknown',
      openSource: false,
      deployer: 'Anonymous · 0 prior launches',
      raised: '$3,380,000',
    },
    reveal: '📜 REAL EVENT — Nov 2021, BSC. 40k buyers. Sell function was completely blocked — a textbook honeypot. Price hit $2,861 then crashed to $0.0007 in minutes. $3.38M stolen. Closed source hid the trap.',
  },
  {
    name: 'Meerkat Finance',
    symbol: 'MKAT',
    difficulty: 'hard',
    outcome: 'rug',
    emoji: '🦡',
    real: true,
    stats: {
      holders: 8000,
      buyTax: '0%',
      sellTax: '0%',
      liquidity: '$31,000,000 (unlocked)',
      topHolder: '12%',
      openSource: false,
      deployer: 'Anonymous · 0 prior launches',
      raised: '$31,000,000',
    },
    reveal: '📜 REAL EVENT — Mar 4 2021, BSC. Drained $31M on day one. Hidden admin function let devs upgrade the vault contract and steal all deposited funds. Largest BSC rug at the time. Closed source concealed the backdoor.',
  },
  {
    name: 'AnubisDAO',
    symbol: 'ANKH',
    difficulty: 'hard',
    outcome: 'rug',
    emoji: '🐺',
    real: true,
    stats: {
      holders: 600,
      buyTax: '0%',
      sellTax: '0%',
      liquidity: '$60,000,000 (unlocked)',
      topHolder: 'Unknown',
      openSource: false,
      deployer: 'Anonymous · 0 prior launches',
      raised: '$60,000,000',
    },
    reveal: '📜 REAL EVENT — Oct 2021, Ethereum. Raised 13,556 ETH (~$60M) in a 20-hour liquidity bootstrapping event. 20 hours later the deployer drained the entire LP. No product, no code — just a dog meme and hype. Biggest single rug by dollar value at the time.',
  },
  {
    name: 'TurtleDex',
    symbol: 'TTDX',
    difficulty: 'medium',
    outcome: 'rug',
    emoji: '🐢',
    real: true,
    stats: {
      holders: 3200,
      buyTax: '0%',
      sellTax: '0%',
      liquidity: '$2,500,000 (unlocked)',
      topHolder: '15%',
      openSource: false,
      deployer: 'Anonymous · 0 prior launches',
      raised: '$2,500,000',
    },
    reveal: '📜 REAL EVENT — Apr 2021, BSC. Appeared to be a legit DEX launch. Devs drained ~$2.5M from the LP pool overnight while users slept. Unlocked liquidity was the critical tell — always check the lock.',
  },
  {
    name: 'SaveTheKids',
    symbol: 'KIDS',
    difficulty: 'medium',
    outcome: 'rug',
    emoji: '👶',
    real: true,
    stats: {
      holders: 12000,
      buyTax: '0%',
      sellTax: '0%',
      liquidity: '$800,000 (unlocked)',
      topHolder: '41%',
      openSource: false,
      deployer: 'Fresh wallet · 0 prior launches',
      raised: '$800,000',
    },
    reveal: '📜 REAL EVENT — Jun 2021, BSC. Promoted by FaZe Clan influencers to their millions of followers. Devs and influencers dumped their pre-allocated 41% on retail buyers. Three FaZe members were suspended. Classic influencer pump-and-dump.',
  },
  {
    name: 'Luna Yield',
    symbol: 'LUNY',
    difficulty: 'easy',
    outcome: 'rug',
    emoji: '🌙',
    real: true,
    stats: {
      holders: 1200,
      buyTax: '0%',
      sellTax: '0%',
      liquidity: '$6,700,000 (unlocked)',
      topHolder: 'Unknown',
      openSource: false,
      deployer: 'Anonymous · 0 prior launches',
      raised: '$6,700,000',
    },
    reveal: '📜 REAL EVENT — Aug 2021, Solana. The first major rug pull on Solana. Anonymous team drained $6.7M in a single night, then deleted all social media and the website. Solana\'s speed made the exit near-instant. Unlocked liquidity + anonymous team = red flags ignored.',
  },

  // REAL MOONS
  {
    name: 'Pepe',
    symbol: 'PEPE',
    difficulty: 'medium',
    outcome: 'moon',
    emoji: '🐸',
    real: true,
    stats: {
      holders: 420,
      buyTax: '0%',
      sellTax: '0%',
      liquidity: '$250,000 (LP burned)',
      topHolder: '5%',
      openSource: true,
      deployer: 'Anonymous · 0 prior launches',
      raised: '$250,000',
    },
    reveal: '📜 REAL EVENT — Apr 2023, Ethereum. Launched silently with 0/0 tax, renounced contract and burned LP. No VC, no presale. Community took over and it became a top-10 meme coin with $1B+ market cap within weeks. Anonymous deployer is fine when the contract is clean.',
  },
  {
    name: 'dogwifhat',
    symbol: 'WIF',
    difficulty: 'hard',
    outcome: 'moon',
    emoji: '🐶',
    real: true,
    stats: {
      holders: 85,
      buyTax: '0%',
      sellTax: '0%',
      liquidity: '$18,000 (locked)',
      topHolder: '18%',
      openSource: true,
      deployer: 'Fresh wallet · 0 prior launches',
      raised: '$18,000',
    },
    reveal: '📜 REAL EVENT — Nov 2023, Solana. 85 holders and $18k raised at launch — looked tiny. Community drove it to a $4B+ market cap within months, making it the #3 meme coin. Low early stats ≠ rug when the fundamentals are clean.',
  },
  {
    name: 'BONK',
    symbol: 'BONK',
    difficulty: 'medium',
    outcome: 'moon',
    emoji: '💕',
    real: true,
    stats: {
      holders: 2100,
      buyTax: '0%',
      sellTax: '0%',
      liquidity: '$120,000 (locked)',
      topHolder: '3%',
      openSource: true,
      deployer: 'Community multisig · 0 prior launches',
      raised: '$120,000',
    },
    reveal: '📜 REAL EVENT — Dec 2022, Solana. Launched as a community Christmas airdrop to Solana NFT holders. 50% of supply airdropped, no VC allocation. Community multisig deployer, locked LP, 0/0 tax. Became Solana\'s first breakout meme coin.',
  },
];

function pickGameTokens(n) {
  const shuffled = [...GAME_TOKENS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(n, shuffled.length));
}
